In [3]:
import numpy as np
a = np.ones((3,4))
a.mean(axis=1)

array([1., 1., 1.])

In [6]:
b = np.arange(1,7).reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b = b - np.mean(b,axis=0)
b

array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])